# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: bionic

addons:
  apt:
    packages:	
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libproj-dev
      - libgeos-dev

matrix:
  include:
  - r: devel
    os: linux
  - r: release
    os: linux
    after_success: travis_wait Rscript -e 'covr::codecov()'
  - r: release
    os: osx



sudo: false
cache: packages
warnings_are_errors: false
r_check_args: "--no-manual --timings"

