codecov:
  branch: master
  strict_yaml_branch: master  # only use the latest copy on master branch

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
        
ignore:
  - "R/UTILS.loadData.R"
  - "R/UTILS.adaptMaps.R"
  - "R/UTILS.upscaleMaps.R"
  - "src"
  - "inst/shinyApp"

fixes:
  - "/home/runner/work/RFate/RFate/::" # Correct paths