codecov:
  branch: master
  strict_yaml_branch: master  # only use the latest copy on master branch

comment: false

coverage:
  precision: 1
  round: down
  range: "50...75"
  status:
    project:
      default:
        target: 75%
        threshold: 1%
      RFate:
        paths:
          - R
      FATE:
        paths:
          - src
      shinyRFate:
        paths:
          - inst/shinyApp
    patch:
      default:
        target: auto
        threshold: 1%
        
ignore:
  - "R/UTILS.loadData.R"
  - "R/UTILS.adaptMaps.R"
  - "R/UTILS.upscaleMaps.R"
  - "src"
  - "inst/shinyApp"

fixes:
  - "/home/runner/work/RFate/RFate/::" # Correct paths