library(testthat)
library(RFate)

# test_check("RFate")

test_file("tests/testthat/test-UTILS.loadPackage.R")
test_file("tests/testthat/test-UTILS.getParam.R")
test_file("tests/testthat/test-UTILS.getCutoff.R")
test_file("tests/testthat/test-UTILS.createParams.R") ## /!\ internal function

test_file("tests/testthat/test-PRE_FATE.abundBraunBlanquet.R")
test_file("tests/testthat/test-PRE_FATE.selectDominant.R")
test_file("tests/testthat/test-PRE_FATE.speciesDistance.R")
test_file("tests/testthat/test-PRE_FATE.speciesClustering_step1.R")
test_file("tests/testthat/test-PRE_FATE.speciesClustering_step2.R")
test_file("tests/testthat/test-PRE_FATE.speciesClustering_step3.R")

test_file("tests/testthat/test-PRE_FATE.skeletonDirectory.R")
test_file("tests/testthat/test-PRE_FATE.params_changingYears.R")
test_file("tests/testthat/test-PRE_FATE.params_savingYears.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGsuccession.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGdispersal.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGlight.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGsoil.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGdisturbance.R")
test_file("tests/testthat/test-PRE_FATE.params_PFGdrought.R")
test_file("tests/testthat/test-PRE_FATE.params_globalParameters.R")
test_file("tests/testthat/test-PRE_FATE.params_simulParameters.R")
test_file("tests/testthat/test-PRE_FATE.params_multipleSet.R")

test_file("tests/testthat/test-POST_FATE.temporalEvolution.R")
test_file("tests/testthat/test-POST_FATE.relativeAbund.R")
test_file("tests/testthat/test-POST_FATE.binaryMaps.R")
test_file("tests/testthat/test-POST_FATE.graphic_evolutionCoverage.R")
test_file("tests/testthat/test-POST_FATE.graphic_evolutionPixels.R")
test_file("tests/testthat/test-POST_FATE.graphic_evolutionStability.R")
test_file("tests/testthat/test-POST_FATE.graphic_validationStatistics.R")
test_file("tests/testthat/test-POST_FATE.graphic_mapPFGvsHS.R")
test_file("tests/testthat/test-POST_FATE.graphic_mapPFG.R")
test_file("tests/testthat/test-POST_FATE.graphics.R")
