---
title: "NEWS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NEWS}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

<style>
.zoom p {
width:250px;
margin-left: auto;
margin-right: auto;
}
.zoom p:hover {
width:900px;
position: relative;
z-index: 10;
}
.column {
  float: left;
  width: 30%;
}
/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>


<br/><br/>


## <i class="fa-solid fa-boxes-stacked"></i> Package releases

Original version was `FATE-HD`, developed and used in papers such as *Boulangeat 2014*, *Barros 2017* or *Carboni 2018* (see [FATE tutorial - Publications](fate_tutorial_0_publications.html)). It was only `C++` code, and all modules were linked together (`LIGHT`, `DISPERSAL`, `HABSUIT`, `SEEDING`, `DISTURBANCE`).

Refinements to the model, and integration of the `C++` code within an `R` package, as well as new modules development, were meant to facilitate the use and spread of the `FATE` model.

<br/> <br/>

#### Version 1.3.2 (october 2023) 

- 1.3.2 : 
    + include PFG loop inside `SuFate::DoDisturbance()` (*optimization*)
    + remove call to `Legion::pickupCohorts()` from `Legion::reduceCohort()` function (*seg fault*)
- 1.3.1 : change scale from `0:10` to `0:100` for `IMM_SIZE`, `ACTIVE_GERM`, `LIGHT_TOL`, `SOIL_TOL`, `PROP_KILLED`, `ACTIVATED_SEED`, `FATES` parameters
- 1.3.0 : addition of `LIGHT_RECRUITMENT` parameter within `LIGHT` module, and `--SOIL_MASK--`, `SOIL_FILL_MAP` and `SOIL_RECRUITMENT` parameters within `SOIL` module (see [FATE tutorial - Modules](fate_tutorial_3_MODULES.html))

<br/> <br/>

#### Version 1.2.0 (april 2023) <a href="https://raw.githubusercontent.com/leca-dev/RFate/master/data-raw/RFate_1.2.0.tar.gz" class="download" title="Download as tar.gz"><i class="fa-solid fa-download"></i></a>

- compatibility with PROJ8
- change BOOST files to update `BH` package from version 1.75 to 1.81
- optimization of `SimulMap` with unswitching
- minor corrections


#### Version 1.1.0 (may 2022) <a href="https://raw.githubusercontent.com/leca-dev/RFate/master/data-raw/RFate_1.1.0.tar.gz" class="download" title="Download as tar.gz"><i class="fa-solid fa-download"></i></a>

- addition of `SHADE_FACTOR` parameter within `LIGHT` module (see [FATE tutorial - Modules](fate_tutorial_3_MODULES.html))
- corrections to seeding recruitment, and environment calculation in `LIGHT` module (height strata)


#### Version 1.0.0 (june 2021) <a href="https://raw.githubusercontent.com/leca-dev/RFate/master/data-raw/RFate_1.0.0.tar.gz" class="download" title="Download as tar.gz"><i class="fa-solid fa-download"></i></a>

- all steps included in one tool (`PRE-FATE`, `FATE`, `POST-FATE`), that can be easily installed on all OS (Mac, Unix, Windows)
- a simplification of some structural equations of the model (see [FATE tutorial - Modelling framework](fate_tutorial_0_modelling_framework.html))
- 8 modules that can be turned on/off (see [FATE tutorial - Modules](fate_tutorial_3_MODULES.html))
- a `shiny` interface for those who prefer to visually explore the parameters (see [SHINY interface](interface_tutorial_0_presentation.html) page)
- a complete documentation and manual, with meaningful examples from real dataset (see [Manual & Examples](manual.html) page)


<br/><br/>


