// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FATE
int FATE(std::string simulParam, int no_CPU, int verboseLevel);
RcppExport SEXP _RFate_FATE(SEXP simulParamSEXP, SEXP no_CPUSEXP, SEXP verboseLevelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type simulParam(simulParamSEXP);
    Rcpp::traits::input_parameter< int >::type no_CPU(no_CPUSEXP);
    Rcpp::traits::input_parameter< int >::type verboseLevel(verboseLevelSEXP);
    rcpp_result_gen = Rcpp::wrap(FATE(simulParam, no_CPU, verboseLevel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RFate_FATE", (DL_FUNC) &_RFate_FATE, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RFate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
