# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FATE Wrapper
#'
#' This function runs a FATE dynamical landscape vegetation simulation.
#'
#' @param simulParam a \code{string} corresponding to the name of a 
#' parameter file that will be contained into the \code{PARAM_SIMUL} folder 
#' of the \code{FATE} simulation
#' @param no_CPU (\emph{optional}) default \code{1}. \cr The number of 
#' resources that can be used to parallelize the simulation
#' @param verboseLevel (\emph{optional}) default \code{0}. \cr The logger 
#' verbose level
#'
#' @return None
#'
#' @examples \dontrun{FATE()}
#'
#' @author Isabelle Boulangeat, \email{isabelle.boulangeat@inrae.fr}
#' @author Maya Guéguen, \email{maya.gueguen@univ-grenoble-alpes.fr}
#'
#' @export
FATE <- function(simulParam, no_CPU = 1L, verboseLevel = 0L) {
    .Call('_RFate_FATE', PACKAGE = 'RFate', simulParam, no_CPU, verboseLevel)
}

