# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CODECOV-check

on:
  push:
    branches: [ RFate ]
  pull_request:
    branches: [ RFate ]
    

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: yarn run test-all
      - name: Upload coverage to Codecov
        uses: ./
        with:
          files: ./coverage/calculator/coverage-final.json,./coverage/index/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-1