# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CODECOV-check

on:
  push:
    branches: [ RFate ]
  pull_request:
    branches: [ RFate ]
    

# Increment this version when we want to clear cache
env:
  cache-version: v1
  r-version: 4.0

jobs:
  test-coverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          r-version: ${{ env.r-version }}

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ env.cache-version }}-macOS-r-${{ env.r-version }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-macOS-r-${{ env.r-version }}-

      - name: Install system dependencies on macOS
        run: |
          # XQuartz is needed by vdiffr
          brew cask install xquartz

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE, type = "binary")
          remotes::install_cran("covr")
        shell: Rscript {0}

      # TODO: Remove remotes::install_github() after covr > 3.5.0 is released
      #       c.f. https://github.com/r-lib/covr/commit/cc710804aeff6f337777465bf902914197c0b713
      - name: Test coverage
        run: |
          remotes::install_github("r-lib/covr")
          covr::codecov()
        shell: Rscript {0}