# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CODECOV-check

on:
  push:
    branches: [ RFate ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master # Check out your repository
    - run: yarn # Install dependencies
    - run: yarn test # Run test
    - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov